"""init all models

Revision ID: 42f86620615f
Revises: cf252f1b26fe
Create Date: 2025-09-06 07:29:07.625554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42f86620615f'
down_revision: Union[str, Sequence[str], None] = 'cf252f1b26fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mc_products', sa.Column('msg', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mc_products', 'msg')
    # ### end Alembic commands ###
