"""init all models

Revision ID: cf68d44fe920
Revises: 42f86620615f
Create Date: 2025-09-06 07:29:49.624074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf68d44fe920'
down_revision: Union[str, Sequence[str], None] = '42f86620615f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mc_products', 'msg')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mc_products', sa.Column('msg', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
